import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bookstore App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="vercel.svg" type="image/x-icon+svg" />
      </head>
      <body className='grid grid-rows[2rem, 1fr, 2rem]'>
        <header>Bookstore App</header>
        {children}
        <footer>All rights reserved</footer>
      </body>
    </html>
  )
}
